# Generated by Django 3.1.6 on 2021-04-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(default='P', max_length=5)),
                ('total', models.CharField(default='none', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('quantity_desc', models.CharField(default=' ', max_length=20)),
                ('desc1', models.CharField(max_length=300)),
                ('desc2', models.CharField(default=' ', max_length=300)),
                ('desc3', models.CharField(default=' ', max_length=300)),
                ('categories', models.CharField(default=' ', max_length=20)),
                ('subcategories', models.CharField(default=' ', max_length=20)),
                ('product_image', models.CharField(default=' ', max_length=50)),
                ('discount_price', models.IntegerField(default=0)),
                ('actual_price', models.IntegerField(default=0)),
                ('save_rs', models.CharField(default='n', max_length=5)),
            ],
        ),
    ]
