# Generated by Django 3.1.6 on 2021-05-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210410_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
